# ============================================================================
# Custom CMake target for Vulkan Memory Allocator.
#
# VMA is header-only by design but the implementation is enabled by defining
# VMA_IMPLEMENTATION in exactly one .cpp file. We provide that here as a
# tiny static library so consumers can link without needing a stub .cpp.
# ============================================================================

set(VMA_DIR "${vma_SOURCE_DIR}")

if(NOT EXISTS "${VMA_DIR}/include/vk_mem_alloc.h")
    message(FATAL_ERROR "VMA sources not found at ${VMA_DIR}")
endif()

# Generate a single .cpp inside the build tree that activates the impl.
set(VMA_IMPL_CPP "${CMAKE_CURRENT_BINARY_DIR}/vma_impl.cpp")
file(WRITE "${VMA_IMPL_CPP}"
"// Auto-generated by cmake/vma.cmake. Do not edit.\n"
"#define VMA_IMPLEMENTATION\n"
"#define VMA_STATIC_VULKAN_FUNCTIONS 1\n"
"#define VMA_DYNAMIC_VULKAN_FUNCTIONS 0\n"
"#include <vk_mem_alloc.h>\n"
)

add_library(vma_impl STATIC "${VMA_IMPL_CPP}")
target_include_directories(vma_impl PUBLIC "${VMA_DIR}/include")
target_link_libraries(vma_impl PUBLIC Vulkan::Vulkan)

# VMA produces noisy warnings under -Wall; quiet them at the source.
if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU" OR CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
    target_compile_options(vma_impl PRIVATE -w)
endif()

# Note: VMA v3.1.0 ships its own CMakeLists which already defines the
# GPUOpen::VulkanMemoryAllocator interface target (headers/usage requirements).
# We deliberately do NOT alias vma_impl over that name — instead, common-cpp
# links GPUOpen::VulkanMemoryAllocator publicly (for headers) and vma_impl
# privately (for the single TU that activates VMA_IMPLEMENTATION).
